// Product catalog + helpers
window.DD_DATA = {
  products: [
    {
      id: 'dd-01',
      name_vi: 'Thanh long ruột trắng — Bình Thuận',
      name_en: 'White Flesh Pitaya — Binh Thuan',
      category: 'white',
      cat_vi: 'Ruột trắng',
      cat_en: 'White flesh',
      price: 32000,
      minOrder: 100,
      size: 'L',
      certs: ['VietGAP', 'GlobalGAP'],
      stock: 'in',
      color: '#F4C2D7',
      accent: '#C4477A',
      featured: true,
      desc_vi: 'Giống thanh long truyền thống, ngọt dịu, giòn nước. Kích cỡ 500–700g, hoàn hảo cho siêu thị và nhà hàng.',
      desc_en: 'Traditional cultivar — mild sweetness, crisp texture. 500–700g, perfect for supermarkets and restaurants.',
    },
    {
      id: 'dd-02',
      name_vi: 'Thanh long ruột đỏ — Long An',
      name_en: 'Red Flesh Pitaya — Long An',
      category: 'red',
      cat_vi: 'Ruột đỏ',
      cat_en: 'Red flesh',
      price: 48000,
      minOrder: 100,
      size: 'L',
      certs: ['VietGAP', 'GlobalGAP', 'HACCP'],
      stock: 'in',
      color: '#E88BAE',
      accent: '#A03460',
      featured: true,
      desc_vi: 'Giống H14 cao cấp, màu đỏ rực, vị ngọt đậm. Brix trung bình 17–19°, thị trường EU và Nhật ưa chuộng.',
      desc_en: 'Premium H14 cultivar — vivid red, rich sweetness. Average 17–19° Brix, popular in EU and Japan.',
    },
    {
      id: 'dd-03',
      name_vi: 'Thanh long vàng Ecuador',
      name_en: 'Yellow Dragon Fruit (Ecuador)',
      category: 'yellow',
      cat_vi: 'Ruột vàng',
      cat_en: 'Yellow flesh',
      price: 135000,
      minOrder: 50,
      size: 'M',
      certs: ['GlobalGAP', 'Organic'],
      stock: 'low',
      color: '#F5E5A8',
      accent: '#C9A961',
      featured: true,
      desc_vi: 'Giống Ecuador quý hiếm, vỏ vàng gai, ruột trắng ngọt ngào. Phù hợp phân khúc cao cấp và xuất khẩu.',
      desc_en: 'Rare Ecuadorian variety — golden spiky skin, sweet white flesh. Top-tier retail and export.',
    },
    {
      id: 'dd-04',
      name_vi: 'Thanh long hữu cơ ruột đỏ',
      name_en: 'Organic Red Dragon Fruit',
      category: 'organic',
      cat_vi: 'Hữu cơ',
      cat_en: 'Organic',
      price: 72000,
      minOrder: 100,
      size: 'L',
      certs: ['USDA Organic', 'EU Organic', 'GlobalGAP'],
      stock: 'in',
      color: '#D98EB0',
      accent: '#8B2F57',
      featured: true,
      desc_vi: 'Đạt chuẩn hữu cơ Hoa Kỳ và EU. Canh tác không thuốc BVTV, phân bón hữu cơ 100%.',
      desc_en: 'Certified organic by USDA and EU. No pesticides, 100% organic fertilizer.',
    },
    {
      id: 'dd-05',
      name_vi: 'Thanh long ruột trắng — size jumbo',
      name_en: 'Jumbo White Pitaya',
      category: 'white',
      cat_vi: 'Ruột trắng',
      cat_en: 'White flesh',
      price: 42000,
      minOrder: 200,
      size: 'XL',
      certs: ['VietGAP', 'GlobalGAP'],
      stock: 'in',
      color: '#FADBE8',
      accent: '#C4477A',
      featured: false,
      desc_vi: 'Trái jumbo trên 700g, trình bày ấn tượng cho khách sạn và nhà hàng cao cấp.',
      desc_en: 'Jumbo fruit over 700g — striking presentation for premium hotels and restaurants.',
    },
    {
      id: 'dd-06',
      name_vi: 'Nước ép thanh long đỏ 250ml',
      name_en: 'Red Pitaya Juice 250ml',
      category: 'processed',
      cat_vi: 'Chế biến',
      cat_en: 'Processed',
      price: 38000,
      minOrder: 240,
      size: 'M',
      certs: ['HACCP', 'ISO 22000'],
      stock: 'in',
      color: '#EBA2C1',
      accent: '#A03460',
      featured: false,
      desc_vi: 'Nước ép thanh long đỏ nguyên chất 100%, không đường, đóng chai thuỷ tinh 250ml.',
      desc_en: '100% pure red pitaya juice — no added sugar, 250ml glass bottle.',
    },
    {
      id: 'dd-07',
      name_vi: 'Thanh long sấy dẻo 200g',
      name_en: 'Dried Dragon Fruit 200g',
      category: 'processed',
      cat_vi: 'Chế biến',
      cat_en: 'Processed',
      price: 95000,
      minOrder: 120,
      size: 'S',
      certs: ['HACCP', 'ISO 22000'],
      stock: 'in',
      color: '#F0B8D0',
      accent: '#8B2F57',
      featured: false,
      desc_vi: 'Sấy dẻo bằng công nghệ sấy lạnh, giữ nguyên 92% dưỡng chất. Hạn 18 tháng.',
      desc_en: 'Freeze-dried — retains 92% nutrients. 18-month shelf life.',
    },
    {
      id: 'dd-08',
      name_vi: 'Mứt thanh long đỏ 320g',
      name_en: 'Red Pitaya Jam 320g',
      category: 'processed',
      cat_vi: 'Chế biến',
      cat_en: 'Processed',
      price: 58000,
      minOrder: 144,
      size: 'M',
      certs: ['HACCP'],
      stock: 'in',
      color: '#D47699',
      accent: '#8B2F57',
      featured: false,
      desc_vi: 'Mứt thanh long đỏ thủ công, 70% trái cây thật, ít đường, thích hợp cho cafe và khách sạn.',
      desc_en: 'Artisanal red pitaya jam — 70% real fruit, low sugar — ideal for cafes and hotels.',
    },
  ],
  certs: [
    { id: 'global', short: 'GLOBAL', name: 'GlobalG.A.P.', since: '2014', desc_vi: 'Canh tác bền vững', desc_en: 'Sustainable farming' },
    { id: 'viet', short: 'VIET', name: 'VietGAP', since: '2012', desc_vi: 'Tiêu chuẩn quốc gia', desc_en: 'National standard' },
    { id: 'usda', short: 'USDA', name: 'USDA Organic', since: '2019', desc_vi: 'Hữu cơ Hoa Kỳ', desc_en: 'US organic' },
    { id: 'eu', short: 'EU', name: 'EU Organic', since: '2020', desc_vi: 'Hữu cơ châu Âu', desc_en: 'European organic' },
    { id: 'haccp', short: 'HACCP', name: 'HACCP', since: '2015', desc_vi: 'An toàn thực phẩm', desc_en: 'Food safety' },
    { id: 'iso', short: 'ISO', name: 'ISO 22000', since: '2016', desc_vi: 'Quản lý chất lượng', desc_en: 'Quality management' },
  ],
  farms: [
    { id: 'bt', x: 38, y: 46, size: 180 },
    { id: 'la', x: 52, y: 68, size: 80 },
    { id: 'tg', x: 58, y: 72, size: 40 },
    { id: 'tv', x: 64, y: 78, size: 20 },
  ],
  timeline: [
    { year: '2011', vi: 'Nông trại đầu tiên tại Bình Thuận, 2 hecta.', en: 'First farm in Binh Thuan — 2 hectares.' },
    { year: '2014', vi: 'Đạt chứng nhận GlobalG.A.P. đầu tiên.', en: 'First GlobalG.A.P. certification.' },
    { year: '2017', vi: 'Xuất khẩu lô đầu tiên sang Hà Lan.', en: 'First export shipment to the Netherlands.' },
    { year: '2019', vi: 'Mở rộng nông trại Long An, đạt chuẩn USDA Organic.', en: 'Long An farm expansion — USDA Organic certified.' },
    { year: '2022', vi: 'Xây dựng nhà máy đóng gói 6.000 m² tại Phan Thiết.', en: 'Built 6,000 m² packing facility in Phan Thiet.' },
    { year: '2026', vi: 'Mạng lưới 28 quốc gia, 120+ đối tác sỉ B2B.', en: 'Network of 28 countries, 120+ B2B partners.' },
  ],
};

window.DD_FMT_VND = (n) => n.toLocaleString('vi-VN') + '₫';
